# Generated by Django 4.1.5 on 2023-04-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_razor_id', models.CharField(max_length=100, unique=True, verbose_name='order id')),
                ('amount', models.IntegerField(verbose_name='total Price')),
                ('jason_data_cart', models.CharField(max_length=500, verbose_name='cart details')),
                ('payment_razor_id', models.CharField(blank=True, default=None, max_length=100, verbose_name='payment id')),
                ('payment_success', models.BooleanField(verbose_name='payment success')),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField(verbose_name='mobile number')),
                ('email_id', models.CharField(max_length=100, verbose_name='email address')),
                ('address', models.TextField()),
                ('city_name', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
                ('order_status', models.CharField(choices=[('In Progress', 'In Progress'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='In Progress', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('razorpay_signature_name', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
    ]
