# Generated by Django 4.1.5 on 2023-04-27 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_orderplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplace',
            name='address',
        ),
        migrations.AddField(
            model_name='orderplace',
            name='address1',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplace',
            name='address2',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplace',
            name='zip_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
