# Generated by Django 4.1.5 on 2023-04-27 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_orderplace_address_orderplace_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplace',
            old_name='customer_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='orderplace',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
