# Generated by Django 4.1.5 on 2023-05-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_customer_name_orderplace_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlace',
        ),
    ]
