# Generated by Django 4.1.5 on 2023-04-30 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSeriesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Test Series Category')),
            ],
            options={
                'verbose_name': 'Test Series Category',
            },
        ),
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('overview', models.CharField(max_length=500)),
                ('isPopularSeries1', models.BooleanField(default=False)),
                ('isNewSeries1', models.BooleanField(default=False)),
                ('test_logo', models.ImageField(blank=True, upload_to='exam_logo/')),
                ('test_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testseries_app.testseriescategory')),
            ],
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_series_name', models.TextField(max_length=100)),
                ('paper_type_test', models.CharField(choices=[('Full Test', 'Full Test'), ('Chapter Test', 'Chapter Test'), ('Sectional Test', 'Sectional Test')], default='Full Test', max_length=100)),
                ('total_marks', models.IntegerField()),
                ('total_question', models.IntegerField()),
                ('test_year', models.DateField()),
                ('isFree', models.BooleanField()),
                ('test_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testseries_app.testseries')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('marks', models.IntegerField()),
                ('is_negative', models.IntegerField(default=0)),
                ('test_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testseries_app.testpaper')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testseries_app.question')),
            ],
        ),
    ]
