# Generated by Django 4.1.5 on 2023-05-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPaperNew',
            fields=[
            ],
            options={
                'verbose_name': 'Test Paper',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testseries_app.testpaper',),
        ),
        migrations.CreateModel(
            name='TestSeriesNew',
            fields=[
            ],
            options={
                'verbose_name': 'Test Series Add',
                'verbose_name_plural': 'Test Series Add',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testseries_app.testseries',),
        ),
        migrations.AlterModelOptions(
            name='testseriescategory',
            options={'verbose_name': 'Test Series Category', 'verbose_name_plural': 'Test Series Category'},
        ),
        migrations.AddField(
            model_name='testpaper',
            name='totalTIme',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testseries',
            name='isNewSeries1',
            field=models.BooleanField(default=False, verbose_name='isUpcoming'),
        ),
    ]
